sudo: required
os:
  - osx
env: JAVA_HOME=$(/usr/libexec/java_home)
language: java
before_install:
- npm install -g cordova@6.5.0
- brew install android-sdk
- wget https://dl.google.com/android/repository/tools_r25.2.3-macosx.zip
- unzip tools_r25.2.3-macosx.zip
- cp -v -rf $PWD/tools/. /usr/local/opt/android-sdk/tools/.
- export ANDROID_HOME=/usr/local/opt/android-sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools/bin
- echo yes | android update sdk -u -a -t 19
- echo yes | android update sdk -u -a -t 20
- echo yes | sdkmanager "build-tools;25.0.2"
- echo yes | sdkmanager "platforms;android-25"
- echo yes | sdkmanager "tools"
- echo yes | sdkmanager "platform-tools"
script: mvn clean install
after_success:
- mvn jacoco:report coveralls:report