sudo: required
os:
  - osx
env: JAVA_HOME=$(/usr/libexec/java_home)
language: java
before_install:
- npm install -g cordova
script: mvn clean install
after_success:
- mvn cobertura:cobertura coveralls:report